[package]
name = "parquet-ui"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wyatt-herkamp/parquet-ui"
description = "A simple UI for viewing Parquet files, built with Rust and Iced."

[dependencies]
arrow = { version = "58.3.0", features = ["chrono-tz"] }
datafusion = "53.1"
iced = { version = "0.14.0", features = ["tokio", "canvas"] }
parquet = "58.3.0"
rfd = "0.17.2"
tokio = { version = "1.52.3", features = ["full"] }
ahash = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
